[package]
name = "rgx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
criterion = "0.4"
tui = "0.19"
crossterm = "0.25"

[[bench]]
name = "filtering_benchmark"
harness = false
